AppBundle\Entity\Contact:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ContactRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
        address:
            type: string
            length: 255
        postalCode:
            type: string
            length: '10'
        town:
            type: string
            length: '100'
    lifecycleCallbacks: {  }
